### PR TITLE
requirements: upgrade various packages

### PR DESCRIPTION
**Pull request by zzzeid**
- babel upgraded from 2.9.1 to 2.10.3
- black upgraded from 22.1.0 to 22.6.0
- bleach upgraded from 4.1.0 to 5.0.1
- certifi upgraded from 2021.10.8 to 2022.6.15
- cffi upgraded from 1.15.0 to 1.15.1
- charset-normalizer upgraded from 2.0.12 to 2.1.0
- click upgraded from 8.0.4 to 8.1.3
- colorama upgraded from 0.4.4 to 0.4.5
- coverage[toml] upgraded from 6.3.2 to 6.4.2
- cryptography upgraded from 36.0.2 to 37.0.4
- imagesize upgraded from 1.3.0 to 1.4.1
- importlib-metadata upgraded from 4.11.3 to 4.12.0
- jeepney upgraded from 0.7.1 to 0.8.0
- jinja2 upgraded from 3.1.0 to 3.1.2
- keyring upgraded from 23.5.0 to 23.7.0
- pkginfo upgraded from 1.8.2 to 1.8.3
- platformdirs upgraded from 2.5.1 to 2.5.2
- pygments upgraded from 2.11.2 to 2.12.0
- pyparsing upgraded from 3.0.7 to 3.0.9
- readme-renderer upgraded from 34.0 to 35.0
- requests upgraded from 2.27.1 to 2.28.1
- secretstorage upgraded from 3.3.1 to 3.3.2
- tqdm upgraded from 4.63.1 to 4.64.0
- typed-ast upgraded from 1.5.2 to 1.5.4
- typing-extensions upgraded from 4.1.1 to 4.3.0
- urllib3 upgraded from 1.26.9 to 1.26.10
- zipp upgraded from 3.7.0 to 3.8.1

### CODE REVIEW

**Review by cgsheeh — APPROVED** [review]
Nit: the title could be change to `requirements: upgrade black to 22.6.0` before landing.

**Comment by zzzeid** [comment]
> Nit: the title could be change to `requirements: upgrade black to 22.6.0` before landing.

The main upgrades are in the .txt files. The black upgrade is due to this issue: https://github.com/psf/black/issues/2964

**Comment by cgsheeh** [comment]
> > Nit: the title could be change to `requirements: upgrade black to 22.6.0` before landing.
> 
> The main upgrades are in the .txt files. The black upgrade is due to this issue: [psf/black#2964](https://github.com/psf/black/issues/2964)

Ah right the other packages with `<=` specifiers are upgraded here too - I saw the change to the `.in` file and assumed this was only upgrading `black` dependencies.

**Comment by zzzeid** [comment]
> Ah right the other packages with `<=` specifiers are upgraded here too - I saw the change to the `.in` file and assumed this was only upgrading `black` dependencies.

Updated the comment to reflect all the upgrades.

**Pull request merged**
